stages:
  data_ingestion:
    cmd: python src/Sentiment/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Sentiment/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion

  data_validation:
    cmd: python src/Sentiment/pipeline/stage_02_data_validation.py
    deps:
      - src/Sentiment/pipeline/stage_02_data_validation.py
      - config/config.yaml
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python src/Sentiment/pipeline/stage_03_data_transformation.py
    deps:
      - src/Sentiment/pipeline/stage_03_data_transformation.py
      - config/config.yaml
    outs:
      - artifacts/data_transformation/sentimentDataset


  training:
    cmd: python src/Sentiment/pipeline/stage_04_model_training.py
    deps:
      - src/Sentiment/pipeline/stage_04_model_training.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_transformation/sentimentDataset
    params:
      - TrainingArguments
    outs:
      - artifacts/model_trainer/LSTMModelV6.h5


  evaluation:
    cmd: python src/Sentiment/pipeline/stage_05_model_evaluation.py
    deps:
      - src/Sentiment/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/data_transformation/sentimentDataset
      - artifacts/model_trainer/LSTMModelV6.h5
    outs:
      - artifacts/model_evaluation/metric.txt